import {
  Shirt,
  RotateCcw,
  FileSearch,
  Store,
  ShoppingCart,
  Megaphone,
  BarChart3,
  ScanLine,
  Cpu,
  Zap,
  Layers,
  Globe,
  Target,
  Palette,
  Rocket,
  Bot,
  Handshake,
  Settings,
  Film,
  Brain,
  MessageCircle,
} from 'lucide-react'

export const ServiceIcons = {
  shirt: Shirt,
  rotate: RotateCcw,
  fileSearch: FileSearch,
  store: Store,
  cart: ShoppingCart,
  megaphone: Megaphone,
  chart: BarChart3,
  scan: ScanLine,
  cpu: Cpu,
  zap: Zap,
  layers: Layers,
  globe: Globe,
  target: Target,
  palette: Palette,
  rocket: Rocket,
  bot: Bot,
  handshake: Handshake,
  settings: Settings,
  film: Film,
  brain: Brain,
  messageCircle: MessageCircle,
}
